# Generated by Django 4.2.2 on 2023-06-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_student_file_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='file',
            field=models.FileField(upload_to='static/filesCo'),
        ),
    ]
