# Generated by Django 4.2.2 on 2023-06-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_student_contact_alter_college_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='file',
            field=models.FileField(upload_to='static/files'),
        ),
    ]
