# Generated by Django 4.2.2 on 2023-06-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_alter_student_file_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='contact',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='file',
            field=models.FileField(default=None, upload_to='static/files'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default=None, upload_to='static/images'),
        ),
    ]
