# Generated by Django 4.2.2 on 2023-06-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_alter_student_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
