# Generated by Django 4.1.5 on 2023-06-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='reciepe_description',
            new_name='receipe_description',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='reciepe_image',
            new_name='receipe_image',
        ),
    ]
