# Generated by Django 4.2.2 on 2023-08-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_subject_subjectmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectMarks',
            new_name='SubjectMark',
        ),
    ]
